version: '3.3'

services:
  celery:
    build: .
    image: celery
    container_name: celery
    restart: always
    command: celery -A application.celery worker -l info
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    command: pipenv run gunicorn 'app:application' -b 0.0.0.0:4000 --timeout 200 --access-logfile -
    volumes:
      - ./static:/app/static
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<ROOT_PASSWORD>
      - MYSQL_DATABASE=<DB_NAME>
      - MYSQL_USER=<USER>
      - MYSQL_PASSWORD=<PASSWORD>
    env_file:
      - ./.env

volumes:
  mysql_data:
