"""create_movie_table

Revision ID: 0a3fed5a8a8b
Revises: 
Create Date: 2023-10-10 10:05:07.032134

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a3fed5a8a8b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("director", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("imdb_score", sa.Float(precision=1), nullable=False),
        sa.Column("popularity", sa.Float(precision=1), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_movies_director"), ["director"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_movies_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_movies_name"))
        batch_op.drop_index(batch_op.f("ix_movies_director"))

    op.drop_table("movies")
    # ### end Alembic commands ###
