"""create_user_table

Revision ID: 98ff5412a9c9
Revises: 0a3fed5a8a8b
Create Date: 2023-10-10 11:37:57.255411

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98ff5412a9c9"
down_revision = "0a3fed5a8a8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email_id", sa.String(length=200), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="userroles"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_full_name"), ["full_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_full_name"))

    op.drop_table("user")
    # ### end Alembic commands ###
